# Generated by Django 2.2.4 on 2019-09-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='mobile',
            field=models.BigIntegerField(null=True),
        ),
    ]
