# Generated by Django 2.2.4 on 2019-09-02 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190902_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='facebook',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='instagram',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='twitter',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
