# Generated by Django 2.2.4 on 2019-09-02 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('weather', models.CharField(max_length=500)),
                ('ldeal_month', models.CharField(max_length=100)),
                ('ideal_duration', models.CharField(max_length=500)),
                ('nearest_airport', models.CharField(max_length=500)),
                ('about', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('place_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('places', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('country', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('themes', models.TextField()),
                ('weather', models.CharField(max_length=500)),
                ('time_required', models.CharField(max_length=500)),
                ('timings', models.CharField(max_length=500)),
                ('entry_fee', models.CharField(max_length=500)),
                ('tripupp_opinion', models.TextField()),
                ('map', models.TextField()),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City')),
            ],
        ),
    ]
