# Generated by Django 2.2.4 on 2019-09-03 11:50

import cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0003_auto_20190902_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='city_pic',
            field=models.ImageField(default='nophoto.jpg', upload_to=cities.models.City.city_pic_path),
        ),
        migrations.AddField(
            model_name='place',
            name='place_pic',
            field=models.ImageField(default='nophoto.jpg', upload_to=cities.models.Place.place_pic_path),
        ),
    ]
