# Generated by Django 2.2.4 on 2019-09-04 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0004_auto_20190903_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theme_name', models.CharField(max_length=500)),
            ],
        ),
    ]
