# Generated by Django 2.2.4 on 2019-09-04 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0005_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='place',
            name='themes',
        ),
        migrations.AddField(
            model_name='place',
            name='themes',
            field=models.ManyToManyField(to='cities.Theme'),
        ),
    ]
