# Generated by Django 2.2.4 on 2019-09-04 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0007_city_themes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='theme',
            options={'verbose_name': 'Theme', 'verbose_name_plural': 'Themes'},
        ),
    ]
