# Generated by Django 2.2.4 on 2019-09-04 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0008_auto_20190904_1436'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='slug',
            field=models.SlugField(default='', editable=False, max_length=500),
        ),
    ]
