# Generated by Django 2.2.4 on 2019-09-09 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0009_theme_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdealMonth',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_name', models.CharField(max_length=20)),
                ('month_number', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='city',
            name='ideal_month',
        ),
        migrations.AddField(
            model_name='city',
            name='ideal_month',
            field=models.ManyToManyField(to='cities.IdealMonth'),
        ),
    ]
