# Generated by Django 2.2.4 on 2019-09-09 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0011_auto_20190909_2314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='Activities',
            new_name='activities',
        ),
        migrations.AddField(
            model_name='city',
            name='region',
            field=models.CharField(default='Across country', max_length=500),
            preserve_default=False,
        ),
    ]
