# Generated by Django 2.2.4 on 2019-09-12 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0013_auto_20190910_0043'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='is_top_destination',
            field=models.BooleanField(default=None),
            preserve_default=False,
        ),
    ]
