# Generated by Django 2.2.4 on 2019-09-16 13:39

import cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0014_city_is_top_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodCuisine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cusine_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FoodDietaryTypes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dietary_type_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FoodFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='FoodMeal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duration_from', models.TimeField()),
                ('duration_to', models.TimeField()),
                ('reach_us', models.TextField()),
                ('minimum_price', models.FloatField()),
                ('maximum_price', models.FloatField()),
                ('food_pic', models.ImageField(default='nophoto.jpg', upload_to=cities.models.Food.food_pic_path)),
                ('cuisine', models.ManyToManyField(to='cities.FoodCuisine')),
                ('dietary_types', models.ManyToManyField(to='cities.FoodDietaryTypes')),
                ('features', models.ManyToManyField(to='cities.FoodFeatures')),
                ('meal', models.ManyToManyField(to='cities.FoodMeal')),
            ],
        ),
    ]
