# Generated by Django 2.2.4 on 2019-09-16 14:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0015_food_foodcuisine_fooddietarytypes_foodfeatures_foodmeal'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='city',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
            preserve_default=False,
        ),
    ]
