# Generated by Django 2.2.4 on 2019-09-17 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0017_auto_20190916_2008'),
    ]

    operations = [
        migrations.CreateModel(
            name='HotelFacility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facility_name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('state', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('star_ratings', models.CharField(choices=[('Budget Hotels', 'Budget Hotels'), ('2 Star Hotels', '2 Star Hotels'), ('3 Star Hotels', '3 Star Hotels'), ('4 Star Hotels', '4 Star Hotels'), ('5 Star Hotels', '5 Star Hotels')], max_length=500)),
                ('hotel_type', models.CharField(choices=[('Apartments', 'Apartments'), ('Residences', 'Residences'), ('Farm stays', 'Farm stays'), ('Resorts', 'Resorts'), ('Hostels', 'Hostels')], max_length=500)),
                ('facilities', models.ManyToManyField(to='cities.HotelFacility')),
            ],
        ),
    ]
