# Generated by Django 2.2.4 on 2019-09-17 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0018_hotel_hotelfacility'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='city',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='cities.City'),
            preserve_default=False,
        ),
    ]
