# Generated by Django 2.2.4 on 2019-09-18 01:33

import cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0019_hotel_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='food_pic',
            field=models.ImageField(default='nophoto.jpg', upload_to=cities.models.Hotel.hotel_pic_path),
        ),
    ]
