# Generated by Django 2.2.4 on 2019-09-18 14:39

import cities.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0020_hotel_food_pic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('duration', models.CharField(max_length=500)),
                ('price', models.FloatField()),
                ('star_ratings', models.IntegerField()),
                ('package_pic', models.ImageField(default='nophoto.jpg', upload_to=cities.models.Package.package_pic_path)),
                ('city', models.ManyToManyField(to='cities.City')),
                ('hotel', models.ManyToManyField(to='cities.Hotel')),
                ('theme', models.ManyToManyField(to='cities.Theme')),
            ],
        ),
    ]
