# Generated by Django 2.2.4 on 2019-09-18 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0021_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.IntegerField(),
        ),
    ]
