# Generated by Django 2.2.4 on 2019-09-18 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0022_auto_20190918_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hotel',
            old_name='food_pic',
            new_name='hotel_pic',
        ),
    ]
