# Generated by Django 2.2.4 on 2019-09-19 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0023_auto_20190918_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hotel',
            name='star_ratings',
            field=models.IntegerField(choices=[(1, 'Budget Hotels'), (2, '2 Star Hotels'), (3, '3 Star Hotels'), (4, '4 Star Hotels'), (5, '5 Star Hotels')]),
        ),
    ]
