# Generated by Django 2.2.4 on 2019-09-19 13:16

import cities.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0024_auto_20190919_1746'),
    ]

    operations = [
        migrations.CreateModel(
            name='photos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_pic', models.ImageField(default='nophoto.jpg', upload_to=cities.models.photos.photo_pic_path)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cities.City')),
                ('theme', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cities.Theme')),
            ],
        ),
    ]
