# Generated by Django 2.2.4 on 2019-09-19 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cities', '0025_photos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photos',
            old_name='package_pic',
            new_name='pic',
        ),
    ]
